### ISSUE TITLE
Ruby Group Capstone : Kanban board

### ISSUE THREAD

**Issue by torobucci** [torobucci/catalog-of-my-things#5]
Hello Reviewer 👋
- [ ] Here is the [link](https://github.com/torobucci/catalog-of-my-things) to our GitHub project
- [ ] We are three members in our team
- [ ] Team member 1 : @ReemMohamedAbdelfatah 
- [ ] Team member 2 : @Odongo006 
- [ ] Team member 3 : @torobucci

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Good job using the right template for your Kanban board

## Required Changes ♻️
- [ ] each bullet point in the [project requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) should have its own card in the kanban board, for example below is the list of group tasks, there are 6 main bullet points this means there need to be at least 6 cards on the board for the group tasks. and the same needs to be done for each individual group member. when doing so please make sure to divide the points (=workload) evenly between each group member.
### Group task

- Create Item class in a separate .rb file.
- All Item class properties visible in the diagram should be defined and set up in the constructor method. Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.
- Add all methods visible in the diagram.
- Implement methods:
    - can_be_archived?() in the Item class
        - should return true if published_date is older than 10 years
        - otherwise, it should return false
    - move_to_archive() in the Item class
        - should reuse can_be_archived?() method
        - should change the archived property to true if the result of the can_be_archived?() method is true
        - should do nothing if the result of the can_be_archived?() method is false
- Create a main.rb file that will serve as your console app entry-point.
- Implement startup actions:
    - Present the user with a list of options to perform.
    - Let users choose an option.
    - If needed, ask for parameters for the option.
    - Have a way to quit the app.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
